/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */


/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum FetchVariant {
  LeafDocument,
  ListDocument,
  ObjectDocument,
} FetchVariant;

typedef enum ReturnOperationVariant {
  StreamReturn,
  SingleReturn,
  CheckReturn,
  ReduceReturn,
} ReturnOperationVariant;

typedef enum PipelineStageVariant {
  Match,
  Insert,
  Put,
  Update,
  Delete,
  Select,
  Sort,
  Require,
  Offset,
  Limit,
  Distinct,
  Reduce,
} PipelineStageVariant;

/**
 * The order of a variable being sorted on in a <code>PipelineStage::Sort</code>
 */
typedef enum SortOrder {
  Ascending,
  Descending,
} SortOrder;

typedef enum VariableAnnotationsVariant {
  InstanceAnnotations,
  TypeAnnotations,
  ValueAnnotations,
} VariableAnnotationsVariant;

typedef enum ConstraintVariant {
  Isa,
  Has,
  Links,
  Sub,
  Owns,
  Relates,
  Plays,
  FunctionCall,
  Expression,
  Is,
  Iid,
  Comparison,
  KindOf,
  Label,
  Value,
  Or,
  Not,
  Try,
} ConstraintVariant;

/**
 * Tells apart exact variants of constraints from the ones allowing subtype-polymorphism.
 * e.g. <code>isa!</code> would be represented as an <code>Constraint::Isa</code>
 * with its exactness field <code>ConstraintExactness::Exact</code>.
 */
typedef enum ConstraintExactness {
  /**
   * Indicates the constraint matches exactly the specified type - e.g. `isa!` or `sub!`
   */
  Exact,
  /**
   * Indicates the constraint matches the specified type and its subtypes - e.g. `isa!` or `sub!`
   */
  Subtypes,
} ConstraintExactness;

/**
 * A representation of the comparator used in a comparison constraint.
 */
typedef enum Comparator {
  Equal,
  NotEqual,
  LessThan,
  LessOrEqual,
  Greater,
  GreaterOrEqual,
  Like,
  Contains,
} Comparator;

/**
 * Kind represents the base of a defined type to describe its capabilities.
 * For example, "define entity person;" defines a type "person" of a kind "entity".
 */
typedef enum Kind {
  /**
   * Entity type kind.
   */
  Entity,
  /**
   * Attribute type kind.
   */
  Attribute,
  /**
   * Relation type kind.
   */
  Relation,
  /**
   * Role type kind (a role played in a relation).
   */
  Role,
} Kind;

typedef enum ConstraintVertexVariant {
  VariableVertex,
  LabelVertex,
  ValueVertex,
  NamedRoleVertex,
} ConstraintVertexVariant;

/**
 * This enum is used to specify the type of the query resulted in this answer.
 *
 * # Examples
 *
 * ```rust
 * concept_row.get_query_type()
 * ```
 */
typedef enum QueryType {
  /**
   * A read-only query (e.g. <code>match</code>).
   */
  ReadQuery,
  /**
   * A data-modifying query (e.g. <code>insert</code>, <code>delete</code>, <code>update</code>).
   */
  WriteQuery,
  /**
   * A schema-modifying query (e.g. <code>define</code>, <code>undefine</code>, <code>redefine</code>).
   */
  SchemaQuery,
} QueryType;

/**
 * <code>ServerRoutingType</code> is used to represent server routing directives in FFI.
 * It is the tag part, which is combined with optional fields to form an instance of the original
 * enum.
 */
typedef enum ServerRoutingType {
  /**
   * Routing decisions are made automatically by the driver.
   */
  Auto,
  /**
   * The driver is pinned to a specific server address.
   */
  Direct,
} ServerRoutingType;

/**
 * This enum is used to specify the replication role of a server.
 */
typedef enum ReplicationRole {
  /**
   * The primary (leader) server in a replicated cluster.
   */
  Primary,
  /**
   * A candidate server eligible for promotion to primary.
   */
  Candidate,
  /**
   * A secondary (follower) server.
   */
  Secondary,
} ReplicationRole;

/**
 * This enum is used to specify the type of transaction.
 *
 * # Examples
 *
 * ```rust
 * database.transaction(TransactionType::Read)
 * ```
 */
typedef enum TransactionType {
  /**
   * Read-only transaction.
   */
  Read = 0,
  /**
   * Data-modifying transaction.
   */
  Write = 1,
  /**
   * Schema-modifying transaction.
   */
  Schema = 2,
} TransactionType;

/**
 * An <code>AnalyzedQuery</code> contains the server's representation of the query and preamble functions;
 * as well as the result of types inferred for each variable by type-inference.
 */
typedef struct AnalyzedQuery AnalyzedQuery;

typedef struct AnalyzedQueryPromise AnalyzedQueryPromise;

/**
 * Promise object representing the result of an asynchronous operation.
 * Use \ref bool_promise_resolve(BoolPromise*) to wait for and retrieve the resulting boolean value.
 */
typedef struct BoolPromise BoolPromise;

/**
 * The fundamental TypeQL object.
 */
typedef struct Concept Concept;

/**
 * Iterator over the <code>Concepts</code>s returned by an API method or query.
 */
typedef struct ConceptIterator ConceptIterator;

/**
 * A single row of concepts representing substitutions for variables in the query.
 * Contains a Header (column names and query type), and the row of optional concepts.
 * An empty concept in a column means the variable does not have a substitution in this answer.
 */
typedef struct ConceptRow ConceptRow;

/**
 * Iterator over the <code>ConceptRow</code>s returned by an API method or query.
 */
typedef struct ConceptRowIterator ConceptRowIterator;

/**
 * A representation of the constraints involved in the query, and types inferred for each variable.
 */
typedef struct Conjunction Conjunction;

/**
 * Holds the index of the conjunction in a <code>Pipeline</code>'s <code>conjunctions</code> field.
 * Used as indirection in the representation of a pipeline.
 */
typedef struct ConjunctionID ConjunctionID;

typedef struct ConjunctionIDIterator ConjunctionIDIterator;

/**
 * The answer to a TypeDB query is a set of concepts which satisfy the <code>Constraints</code> in the query.
 * A <code>ConstraintVertex</code> is either a variable, or some identifier of the concept.
 *
 * * A <code>Variable</code> is a vertex the query must match and return.
 * * A <code>Label</code> uniquely identifies a type
 * * A <code>Value</code> represents a primitive value literal in TypeDB.
 * * A <code>NamedRole</code> vertex is used in links & relates constraints, as multiple relations may have roles with the same name.
 *
 * The types inferred for <code>Variable</code>, <code>Label</code> and <code>NamedRole</code> vertices
 * can be read from the <code>variable_annotations</code> field of the <code>Conjunction</code> it is in.
 */
typedef struct ConstraintVertex ConstraintVertex;

typedef struct ConstraintVertexIterator ConstraintVertexIterator;

typedef struct ConstraintWithSpan ConstraintWithSpan;

typedef struct ConstraintWithSpanIterator ConstraintWithSpanIterator;

/**
 * User credentials for connecting to TypeDB
 */
typedef struct Credentials Credentials;

/**
 * A TypeDB database.
 */
typedef struct Database Database;

/**
 * An <code>Iterator</code> over databases present on the TypeDB server.
 */
typedef struct DatabaseIterator DatabaseIterator;

/**
 * TypeDB driver connection options.
 * `DriverOptions` object can be used to override the default driver behavior while connecting to
 * TypeDB.
 *
 * # Examples
 *
 * ```rust
 * let options = DriverOptions::new(DriverTlsConfig::default()).request_timeout(Duration::from_secs(30));
 * ```
 */
typedef struct DriverOptions DriverOptions;

/**
 * TLS configuration for the TypeDB driver.
 *
 * `DriverTlsConfig` represents a fully constructed and validated TLS configuration.
 * If TLS is enabled, the underlying TLS config is built eagerly at construction time,
 * ensuring that no connection attempt can observe a partially-configured TLS state.
 *
 * The driver defaults to using TLS with **native system trust roots**.
 * This matches typical system and container deployments while still allowing
 * explicit opt-out or custom PKI configuration.
 */
typedef struct DriverTlsConfig DriverTlsConfig;

/**
 * Represents errors encountered during operation.
 */
typedef struct Error Error;

/**
 * A representation of the 'fetch' stage of a query
 */
typedef struct Fetch Fetch;

/**
 * Holds a representation of the function, and the result of type-inference for each variable.
 */
typedef struct Function Function;

typedef struct FunctionIterator FunctionIterator;

/**
 * A <code>NamedRole</code> vertex is used in links & relates constraints, as multiple relations may have roles with the same name.
 */
typedef struct NamedRole NamedRole;

/**
 * A representation of a query pipeline.
 */
typedef struct Pipeline Pipeline;

/**
 * Representation of a stage in a <code>Pipeline</code>.
 */
typedef struct PipelineStage PipelineStage;

typedef struct PipelineStageIterator PipelineStageIterator;

typedef struct QueryAnswer QueryAnswer;

/**
 * Promise object representing the result of an asynchronous operation.
 * Use \ref query_answer_promise_resolve(QueryAnswerPromise*) to wait for and retrieve the resulting boolean value.
 */
typedef struct QueryAnswerPromise QueryAnswerPromise;

/**
 * TypeDB query options.
 * `QueryOptions` object can be used to override the default server behaviour for executed queries.
 *
 * # Examples
 *
 * ```rust
 * let options = QueryOptions::new().include_instance_types(true);
 * ```
 */
typedef struct QueryOptions QueryOptions;

/**
 * Representation of an assignment from a reduction in a <code>PipelineStage::Reduce</code>,
 * such as <code>reduce $c = sum($x);</code>
 */
typedef struct ReduceAssignment ReduceAssignment;

typedef struct ReduceAssignmentIterator ReduceAssignmentIterator;

/**
 * Representation of a reducer used either in a <code>PipelineStage::Reduce</code>
 * or in a function's <code>ReturnOperation</code>.
 */
typedef struct Reducer Reducer;

typedef struct ReducerIterator ReducerIterator;

/**
 * A representation of the return operation of the function
 */
typedef struct ReturnOperation ReturnOperation;

/**
 * The metadata and state of an individual server of a driver connection.
 */
typedef struct Server Server;

/**
 * Iterator over the <code>Server</code> corresponding to each server of a TypeDB cluster.
 */
typedef struct ServerIterator ServerIterator;

/**
 * The variable being sorted on and the ordering of the sort, as used in a <code>PipelineStage::Sort</code>,
 *  e.g. <code>sort $v desc</code>
 */
typedef struct SortVariable SortVariable;

typedef struct SortVariableIterator SortVariableIterator;

/**
 * Iterator over the <code>StringAndOptValue</code>s representing struct value {field_name: value?} info.
 */
typedef struct StringAndOptValueIterator StringAndOptValueIterator;

/**
 * Iterator over the strings in the result of a request or a TypeQL Fetch query.
 */
typedef struct StringIterator StringIterator;

/**
 * Promise object representing the result of an asynchronous operation.
 * Use \ref string_promise_resolve(StringPromise*) to wait for and retrieve the resulting string.
 */
typedef struct StringPromise StringPromise;

/**
 * A transaction with a TypeDB database.
 */
typedef struct Transaction Transaction;

/**
 * TypeDB transaction options.
 * `TransactionOptions` object can be used to override the default behaviour for opened
 * transactions.
 *
 * # Examples
 *
 * ```rust
 * let options = TransactionOptions::new().transaction_timeout(Duration::from_secs(60));
 * ```
 */
typedef struct TransactionOptions TransactionOptions;

/**
 * A connection to a TypeDB server which serves as the starting point for all interaction.
 */
typedef struct TypeDBDriver TypeDBDriver;

/**
 * A TypeDB server user, identified by a username.
 */
typedef struct User User;

/**
 * Iterator over a set of <code>User</code>s.
 */
typedef struct UserIterator UserIterator;

/**
 * Uniquely identifies a variable in a <code>Pipeline</code>pipeline.
 * Its name (if any) can be retrieved from the <code>variable_names</code> field in <code>Pipeline</code>
 */
typedef struct Variable Variable;

typedef struct VariableAnnotations VariableAnnotations;

typedef struct VariableAnnotationsIterator VariableAnnotationsIterator;

typedef struct VariableIterator VariableIterator;

/**
 * Promise object representing the result of an asynchronous operation.
 * A VoidPromise does not return a value, but must be resolved using \ref void_promise_resolve(VoidPromise*)
 * to ensure the operation has completed, or for a failed operation to set the error.
 */
typedef struct VoidPromise VoidPromise;

/**
 * A <code>DatetimeInNanos</code> used to represent datetime as a pair of seconds part and
 * a number of nanoseconds since the last seconds boundary.
 */
typedef struct DatetimeInNanos {
  /**
   * Whole seconds since the Unix epoch.
   */
  int64_t seconds;
  /**
   * Nanoseconds elapsed since the last whole-second boundary.
   */
  uint32_t subsec_nanos;
} DatetimeInNanos;

/**
 * <code>DatetimeAndTimeZone</code> is used to represent time zoned datetime in FFI.
 * Time zone can be represented either as an IANA <code>Tz</code> or as a <code>FixedOffset</code>.
 * Either the zone_name (is_fixed_offset == false) or offset (is_fixed_offset == true) is set.
 */
typedef struct DatetimeAndTimeZone {
  /**
   * The datetime expressed as a (seconds, subsec_nanos) pair.
   */
  struct DatetimeInNanos datetime_in_nanos;
  /**
   * IANA time zone identifier (e.g. <code>"Europe/London"</code>); set when <code>is_fixed_offset</code> is false.
   */
  char *zone_name;
  /**
   * Offset from UTC in seconds; set when <code>is_fixed_offset</code> is true.
   */
  int32_t local_minus_utc_offset;
  /**
   * True if the time zone is a fixed offset, false if it is an IANA-named zone.
   */
  bool is_fixed_offset;
} DatetimeAndTimeZone;

/**
 * A <code>StringAndOptValue</code> used to represent the pair of variables involved in an ownership.
 * <code>_0</code> and <code>_1</code> are the owner and attribute variables respectively.
 */
typedef struct StringAndOptValue {
  /**
   * The string component of the pair (e.g. a struct field name).
   */
  char *string;
  /**
   * Optional <code>Concept</code> value associated with the string; may be null.
   */
  struct Concept *value;
} StringAndOptValue;

/**
 * A fixed-point decimal number.
 * Holds exactly 19 digits after the decimal point and a 64-bit value before the decimal point.
 */
typedef struct Decimal {
  /**
   * The integer part of the decimal as normal signed 64 bit number
   */
  int64_t integer;
  /**
   * The fractional part of the decimal, in multiples of 10^-19 (Decimal::FRACTIONAL_PART_DENOMINATOR).
   * This means that the smallest decimal representable is 10^-19, and up to 19 decimal places are supported.
   */
  uint64_t fractional;
} Decimal;

/**
 * A relative duration, which contains months, days, and nanoseconds.
 * Can be used for calendar-relative durations (eg 7 days forward), or for absolute durations using the nanosecond component
 * When used as an absolute duration, convertible to chrono::Duration
 */
typedef struct Duration {
  /**
   * Number of calendar months in the duration.
   */
  uint32_t months;
  /**
   * Number of calendar days in the duration.
   */
  uint32_t days;
  /**
   * Number of nanoseconds in the duration.
   */
  uint64_t nanos;
} Duration;
/**
 * Number of nanoseconds in one second.
 */
#define Duration_NANOS_PER_SEC 1000000000
/**
 * Number of days in one week.
 */
#define Duration_DAYS_PER_WEEK 7
/**
 * Number of months in one year.
 */
#define Duration_MONTHS_PER_YEAR 12

/**
 * <code>ServerVersion</code> is an FFI representation of a full server's version specification.
 */
typedef struct ServerVersion {
  /**
   * Distribution name (e.g. <code>"typedb"</code>, <code>"typedb-cluster"</code>).
   */
  char *distribution;
  /**
   * Distribution version string (e.g. <code>"3.7.0"</code>).
   */
  char *version;
} ServerVersion;

/**
 * <code>ServerRouting</code> is used to represent server routing directives in FFI.
 * It combines <code>ServerRoutingType</code> and optional fields to form an instance of the
 * original enum.
 * <code>address</code> is not null only when tag is <code>Direct</code>.
 */
typedef struct ServerRouting {
  /**
   * The routing variant.
   */
  enum ServerRoutingType type_;
  /**
   * Target server address; non-null only when <code>type_</code> is <code>Direct</code>.
   */
  char *address;
} ServerRouting;

/**
 * Enables logging in the TypeDB driver.
 *
 * This function sets up tracing with two environment variables:
 *
 * - `TYPEDB_DRIVER_LOG`: Fine-grained control using the same syntax as `RUST_LOG`.
 *   Example: `TYPEDB_DRIVER_LOG=typedb_driver=debug,typedb_driver_clib=trace`
 *
 * - `TYPEDB_DRIVER_LOG_LEVEL`: Simple log level that applies to both `typedb_driver`
 *   and `typedb_driver_clib` crates. Overrides any settings from `TYPEDB_DRIVER_LOG`.
 *   Example: `TYPEDB_DRIVER_LOG_LEVEL=debug`
 *
 * If neither is set, the default level is INFO for driver crates.
 *
 * The logging is initialized only once to prevent multiple initializations
 * in applications that create multiple drivers.
 */
void init_logging(void);

/**
 * Waits for and returns the result of the Analyze request.
 * In case the operation failed, the error flag will only be set when the promise is resolved.
 * The native promise object is freed when it is resolved.
 */
struct AnalyzedQuery *analyzed_query_promise_resolve(struct AnalyzedQueryPromise *promise);

/**
 * Frees the native rust <code>AnalyzePromise</code> object.
 */
void analyzed_query_promise_drop(struct AnalyzedQueryPromise *promise);

/**
 * Returns the structure of the query pipeline in the analyzed query.
 */
struct Pipeline *analyzed_query_pipeline(const struct AnalyzedQuery *analyzed_query);

/**
 * Returns the analyzed functions in the preamble of the query.
 */
struct FunctionIterator *analyzed_preamble(const struct AnalyzedQuery *analyzed_query);

/**
 * Returns the analyzed fetch
 */
struct Fetch *analyzed_fetch(const struct AnalyzedQuery *analyzed_query);

/**
 * Returns the variant of the <code>Fetch</code> instance.
 */
enum FetchVariant fetch_variant(const struct Fetch *fetch);

/**
 * Unwraps the <code>Fetch</code> instance as a Leaf variant, and returns an iterator over possible value types.
 * Will panic if the instance is not a Leaf variant.
 */
struct StringIterator *fetch_leaf_annotations(const struct Fetch *fetch);

/**
 * Unwraps the <code>Fetch</code> instance as a List variant, and returns the <code>Fetch</code> for an element of the list.
 * Will panic if the instance is not a List variant.
 */
struct Fetch *fetch_list_element(const struct Fetch *fetch);

/**
 * Unwraps the <code>Fetch</code> instance as an Object variant, and returns the available fields.
 * Will panic if the instance is not an Object variant.
 */
struct StringIterator *fetch_object_fields(const struct Fetch *fetch);

/**
 * Unwraps the <code>Fetch</code> instance as an Object variant, and returns the value of the specified field.
 * Will panic if the instance is not an Object variant.
 */
struct Fetch *fetch_object_get_field(const struct Fetch *fetch,
                                     const char *field);

/**
 * A representation of the <code>Pipeline</code> which forms the body of the function.
 */
struct Pipeline *function_body(const struct Function *function);

/**
 * Returns the <code>Variable</code>s which are the arguments of the function.
 */
struct VariableIterator *function_argument_variables(const struct Function *function);

/**
 * A representation of the <code>ReturnOperation</code> of the function.
 */
struct ReturnOperation *function_return_operation(const struct Function *function);

/**
 * Returns the variant of the <code>ReturnOperation</code>.
 */
enum ReturnOperationVariant return_operation_variant(const struct ReturnOperation *return_operation);

/**
 * Unwraps the <code>ReturnOperation</code> instance as a Stream variant, and returns the returned variables.
 * Will panic if the instance is not a Stream variant.
 */
struct VariableIterator *return_operation_stream_variables(const struct ReturnOperation *return_operation);

/**
 * Unwraps the <code>ReturnOperation</code> instance as a Single variant, and returns the returned variables.
 * Will panic if the instance is not a Single variant.
 */
struct VariableIterator *return_operation_single_variables(const struct ReturnOperation *return_operation);

/**
 * Unwraps the <code>ReturnOperation</code> instance as a Single variant, and returns the selector applied.
 * Will panic if the instance is not a Single variant.
 */
char *return_operation_single_selector(const struct ReturnOperation *return_operation);

/**
 * Unwraps the <code>ReturnOperation</code> instance as a Reduce variant, and returns the reducers applied.
 * Will panic if the instance is not a Reduce variant.
 */
struct ReducerIterator *return_operation_reducers(const struct ReturnOperation *return_operation);

/**
 * Returns the inferred type for each argument of the function.
 */
struct VariableAnnotationsIterator *function_argument_annotations(const struct Function *function);

/**
 * Returns the inferred type for each concept returned by the function.
 */
struct VariableAnnotationsIterator *function_return_annotations(const struct Function *function);

/**
 * Returns an iterator over the stages making up the <code>Pipeline</code>
 */
struct PipelineStageIterator *pipeline_stages(const struct Pipeline *pipeline);

/**
 * Returns the variant of the <code>Pipeline</code> stage.
 */
enum PipelineStageVariant pipeline_stage_variant(const struct PipelineStage *stage);

/**
 * Returns a string representation of the pipeline stage
 */
char *pipeline_stage_string_repr(const struct PipelineStage *stage);

/**
 * Returns the block of the pipeline stage - this is the <code>ConjunctionID</code> of the root conjunction.
 * Will panic if the stage does not have a block.
 */
struct ConjunctionID *pipeline_stage_get_block(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Delete stage, and returns the variables deleted.
 * Will panic if the stage is not a Delete.
 */
struct VariableIterator *pipeline_stage_delete_get_deleted_variables(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Select stage, and returns the variables selected.
 * Will panic if the stage is not a Select.
 */
struct VariableIterator *pipeline_stage_select_get_variables(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Require stage, and returns the required variables.
 * Will panic if the stage is not a Require stage.
 */
struct VariableIterator *pipeline_stage_require_get_variables(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as an Offset stage, and returns the offset applied.
 * Will panic if the stage is not an Offset stage.
 */
int64_t pipeline_stage_offset_get_offset(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Limit stage, and returns the limit applied.
 * Will panic if the stage is not a Limit stage.
 */
int64_t pipeline_stage_limit_get_limit(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Sort stage, and returns the <code>SortVariable</code>.
 * Will panic if the stage is not a Sort stage.
 */
struct SortVariableIterator *pipeline_stage_sort_get_sort_variables(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Reduce stage, and returns the variables being grouped on.
 * Will panic if the stage is not a Reduce stage.
 */
struct VariableIterator *pipeline_stage_reduce_get_groupby(const struct PipelineStage *stage);

/**
 * Unwraps the <code>PipelineStage</code> instance as a Reduce stage,
 *  and returns the reducers applied and the variables their results are assigned to.
 * Will panic if the stage is not a Reduce stage.
 */
struct ReduceAssignmentIterator *pipeline_stage_reduce_get_reducer_assignments(const struct PipelineStage *stage);

/**
 * Returns the variable being sorted on.
 */
struct Variable *sort_variable_get_variable(const struct SortVariable *sort_variable);

/**
 * Returns the sort order for the variable being sorted on.
 */
enum SortOrder sort_variable_get_order(const struct SortVariable *sort_variable);

/**
 * The variable being assigned to in this ReduceAssignment.
 * e.g. `$c` in <code>$c = sum($x)</code>
 */
struct Variable *reduce_assignment_get_assigned(const struct ReduceAssignment *reduce_assignment);

/**
 * The reducer applied in this ReduceAssignment.
 * e.g. `sum($x)` in <code>$c = sum($x)</code>
 */
struct Reducer *reduce_assignment_get_reducer(const struct ReduceAssignment *reduce_assignment);

/**
 * The name of the operation applied by this Reducer.
 * e.g. `sum` in <code>sum($x)</code>
 */
char *reducer_get_name(const struct Reducer *reducer);

/**
 * The arguments to this Reducer.
 * e.g. `$x` in <code>sum($x)</code>
 */
struct VariableIterator *reducer_get_arguments(const struct Reducer *reducer);

/**
 * Returns the name of the specified variable if it has one, and null otherwise.
 * The <code>Pipeline</code> must be the one that contains the variable.
 */
char *variable_get_name(const struct Pipeline *pipeline_structure, const struct Variable *variable);

/**
 * Returns the Variable id as u32 to use in hash, equality etc.
 */
uint32_t variable_id_as_u32(const struct Variable *variable);

/**
 * Returns a string representation of the variable. Does not resolve the name.
 */
char *variable_string_repr(const struct Variable *variable);

/**
 * Returns the <code>Conjunction</code> corresponding to the ConjunctionID.
 * The <code>Pipeline</code> must be the one that contains the Conjunction & ConjunctionID.
 */
struct Conjunction *pipeline_get_conjunction(const struct Pipeline *pipeline,
                                             const struct ConjunctionID *conjunction_id);

/**
 * Returns the ConjunctionID as u32 to use in hash, equality etc.
 */
uint32_t conjunction_id_as_u32(const struct ConjunctionID *conjunction_id);

/**
 * Returns a string representation of the ConjunctionID.
 */
char *conjunction_id_string_repr(const struct ConjunctionID *conjunction_id);

/**
 * Returns the <code>Constraint</code>s in the given conjunction.
 */
struct ConstraintWithSpanIterator *conjunction_get_constraints(const struct Conjunction *conjunction);

/**
 * Returns the variables in the current conjunction for which type annotations are available
 */
struct VariableIterator *conjunction_get_annotated_variables(const struct Conjunction *conjunction);

/**
 * Returns the inferred types for the specified variable in the specified conjunction.
 */
struct VariableAnnotations *conjunction_get_variable_annotations(const struct Conjunction *conjunction,
                                                                 const struct Variable *variable);

/**
 * Returns the variant of the specified VariableAnnotations.
 * This tells us whether the variable holds an instance, a type or a raw value.
 */
enum VariableAnnotationsVariant variable_annotations_variant(const struct VariableAnnotations *annotations);

/**
 * Unwraps the <code>VariableAnnotations</code> instance as annotations for an Instance variable,
 *  and returns the possible types of the instances the variable may hold.
 * Will panic if the variable is not an Instance variable.
 */
struct ConceptIterator *variable_annotations_instance(const struct VariableAnnotations *annotations);

/**
 * Unwraps the <code>VariableAnnotations</code> instance as annotations for a Type variable,
 *  and returns the possible types the variable may be.
 * Will panic if the variable is not a Type variable.
 */
struct ConceptIterator *variable_annotations_type(const struct VariableAnnotations *annotations);

/**
 * Unwraps the <code>VariableAnnotations</code> instance as annotations for a Value variable,
 *  and returns the possible ValueTypes the value may be.
 * Will panic if the variable is not a Value variable.
 */
struct StringIterator *variable_annotations_value(const struct VariableAnnotations *annotations);

/**
 * The offset of the first character of the specified constraint in the source query .
 */
int64_t constraint_span_begin(const struct ConstraintWithSpan *constraint);

/**
 * The offset after the last character of the specified constraint in the source query .
 */
int64_t constraint_span_end(const struct ConstraintWithSpan *constraint);

/**
 * The variant of the specified constraint
 */
enum ConstraintVariant constraint_variant(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Isa` constraint,
 *  and returns the instance vertex.
 * Will panic if the Constraint is not an Isa constraint.
 */
struct ConstraintVertex *constraint_isa_get_instance(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Isa` constraint,
 *  and returns the type vertex.
 * Will panic if the Constraint is not an Isa constraint.
 */
struct ConstraintVertex *constraint_isa_get_type(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Has` constraint,
 * and returns the owner vertex.
 * Will panic if the Constraint is not a Has constraint.
 */
struct ConstraintVertex *constraint_has_get_owner(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Has` constraint,
 * and returns the attribute vertex.
 * Will panic if the Constraint is not a Has constraint.
 */
struct ConstraintVertex *constraint_has_get_attribute(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Links` constraint,
 * and returns the relation vertex.
 * Will panic if the Constraint is not a Links constraint.
 */
struct ConstraintVertex *constraint_links_get_relation(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Links` constraint,
 * and returns the player vertex.
 * Will panic if the Constraint is not a Links constraint.
 */
struct ConstraintVertex *constraint_links_get_player(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Links` constraint,
 * and returns the role vertex.
 * Will panic if the Constraint is not a Links constraint.
 */
struct ConstraintVertex *constraint_links_get_role(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Sub` constraint,
 * and returns the subtype vertex.
 * Will panic if the Constraint is not a Sub constraint.
 */
struct ConstraintVertex *constraint_sub_get_subtype(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Sub` constraint,
 * and returns the supertype vertex.
 * Will panic if the Constraint is not a Sub constraint.
 */
struct ConstraintVertex *constraint_sub_get_supertype(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Owns` constraint,
 * and returns the owner-type vertex.
 * Will panic if the Constraint is not an Owns constraint.
 */
struct ConstraintVertex *constraint_owns_get_owner(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Owns` constraint,
 * and returns the attribute-type vertex.
 * Will panic if the Constraint is not an Owns constraint.
 */
struct ConstraintVertex *constraint_owns_get_attribute(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Relates` constraint,
 * and returns the relation-type vertex.
 * Will panic if the Constraint is not a Relates constraint.
 */
struct ConstraintVertex *constraint_relates_get_relation(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Relates` constraint,
 * and returns the role-type vertex.
 * Will panic if the Constraint is not a Relates constraint.
 */
struct ConstraintVertex *constraint_relates_get_role(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Plays` constraint,
 * and returns the player type vertex.
 * Will panic if the Constraint is not a Plays constraint.
 */
struct ConstraintVertex *constraint_plays_get_player(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Plays` constraint,
 * and returns the role-type vertex.
 * Will panic if the Constraint is not a Plays constraint.
 */
struct ConstraintVertex *constraint_plays_get_role(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Isa` constraint,
 * and returns the exactness of the type match.
 * Will panic if the Constraint is not an Isa constraint.
 */
enum ConstraintExactness constraint_isa_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * (FUTURE-USE: Currently always ConstraintExactness::Subtypes)
 * Unwraps the <code>Constraint</code> instance as a `Has` constraint,
 * and returns the exactness of the attribute match.
 * Will panic if the Constraint is not a Has constraint.
 */
enum ConstraintExactness constraint_has_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * (FUTURE-USE: Currently always ConstraintExactness::Subtypes)
 * Unwraps the <code>Constraint</code> instance as a `Links` constraint,
 * and returns the exactness of the role-type match.
 * Will panic if the Constraint is not a Links constraint.
 */
enum ConstraintExactness constraint_links_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Sub` constraint,
 * and returns the exactness of the subtype match.
 * If Exact (i.e. `sub!`), only the immediate subtype is returned
 * else, (i.e. `sub`) the type itself and all subtypes are returned.
 * Will panic if the Constraint is not a Sub constraint.
 */
enum ConstraintExactness constraint_sub_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * (FUTURE-USE: Currently always ConstraintExactness::Subtypes)
 * Will panic if the Constraint is not an Owns constraint.
 */
enum ConstraintExactness constraint_owns_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Relates` constraint,
 * and returns the exactness of the relation match.
 * Will panic if the Constraint is not a Relates constraint.
 */
enum ConstraintExactness constraint_relates_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * (FUTURE-USE: Currently always ConstraintExactness::Subtypes)
 */
enum ConstraintExactness constraint_plays_get_exactness(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `FunctionCall` constraint,
 * and returns the function name.
 * Will panic if the Constraint is not a FunctionCall constraint.
 */
char *constraint_function_call_get_name(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `FunctionCall` constraint,
 * and returns the variables assigned by the function call.
 * Will panic if the Constraint is not a FunctionCall constraint.
 */
struct ConstraintVertexIterator *constraint_function_call_get_assigned(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `FunctionCall` constraint,
 * and returns the variables passed as arguments to the function call .
 * Will panic if the Constraint is not a FunctionCall constraint.
 */
struct ConstraintVertexIterator *constraint_function_call_get_arguments(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Expression` constraint,
 * and returns the expression text.
 * Will panic if the Constraint is not an Expression constraint.
 */
char *constraint_expression_get_text(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Expression` constraint,
 * and returns the variable assigned by the expression.
 * Will panic if the Constraint is not an Expression constraint.
 */
struct ConstraintVertex *constraint_expression_get_assigned(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Expression` constraint,
 * and returns the expression arguments -
 * These are any variables used in the right-hand side of the expression.
 * Will panic if the Constraint is not an Expression constraint.
 */
struct ConstraintVertexIterator *constraint_expression_get_arguments(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Is` constraint,
 * and returns the left-hand side vertex.
 * Will panic if the Constraint is not an Is constraint.
 */
struct ConstraintVertex *constraint_is_get_lhs(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Is` constraint,
 * and returns the right-hand side vertex.
 * Will panic if the Constraint is not an Is constraint.
 */
struct ConstraintVertex *constraint_is_get_rhs(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Iid` constraint,
 * and returns the concept (variable) the iid applies to.
 * Will panic if the Constraint is not an Iid constraint.
 */
struct ConstraintVertex *constraint_iid_get_variable(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Iid` constraint,
 * and returns the iid value as a string.
 * Will panic if the Constraint is not an Iid constraint.
 */
char *constraint_iid_get_iid(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Comparison` constraint,
 * and returns the left-hand side vertex.
 * Will panic if the Constraint is not a Comparison constraint.
 */
struct ConstraintVertex *constraint_comparison_get_lhs(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Comparison` constraint,
 * and returns the right-hand side vertex.
 * Will panic if the Constraint is not a Comparison constraint.
 */
struct ConstraintVertex *constraint_comparison_get_rhs(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Comparison` constraint,
 * and returns the comparator used in the comparison.
 * Will panic if the Constraint is not a Comparison constraint.
 */
enum Comparator constraint_comparison_get_comparator(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Comparator</code> and returns its name (or symbol).
 */
char *comparator_get_name(enum Comparator comparator);

/**
 * Unwraps the <code>Constraint</code> instance as a `Kind` constraint,
 * and returns the `Kind` of the type-vertex.
 * Will panic if the Constraint is not a Kind constraint.
 */
enum Kind constraint_kind_get_kind(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Kind` constraint,
 * and returns the associated type vertex.
 * Will panic if the Constraint is not a Kind constraint.
 */
struct ConstraintVertex *constraint_kind_get_type(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Label` constraint,
 * and returns the type-vertex the label applies to.
 * Will panic if the Constraint is not a Label constraint.
 */
struct ConstraintVertex *constraint_label_get_variable(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Label` constraint,
 * and returns the label string.
 * Will panic if the Constraint is not a Label constraint.
 */
char *constraint_label_get_label(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Value` constraint,
 * and returns the attribute type vertex.
 * Will panic if the Constraint is not a Value constraint.
 */
struct ConstraintVertex *constraint_value_get_attribute_type(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Value` constraint,
 * and returns the specified ValueType as a string.
 * Will panic if the Constraint is not a Value constraint.
 */
char *constraint_value_get_value_type(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as an `Or` constraint,
 * and returns the <code>ConjunctionID</code>s of the conjunction in each of the branches.
 * Will panic if the Constraint is not an Or constraint.
 */
struct ConjunctionIDIterator *constraint_or_get_branches(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Not` constraint,
 * and returns the <code>ConjunctionID</code> of the negated conjunction.
 * Will panic if the Constraint is not a Not constraint.
 */
struct ConjunctionID *constraint_not_get_conjunction(const struct ConstraintWithSpan *constraint);

/**
 * Unwraps the <code>Constraint</code> instance as a `Try` constraint,
 * and returns the <code>ConjunctionID</code> of the optionally matched conjunction.
 * Will panic if the Constraint is not a Try constraint.
 */
struct ConjunctionID *constraint_try_get_conjunction(const struct ConstraintWithSpan *constraint);

/**
 * Returns a string representation of the constraint
 */
char *constraint_string_repr(const struct ConstraintWithSpan *constraint);

/**
 * Returns the variant of the constraint
 */
enum ConstraintVertexVariant constraint_vertex_variant(const struct ConstraintVertex *vertex);

/**
 * Unwraps the <code>ConstraintVertex</code> instance as a Variable.
 *  Will panic if the instance is not a Variable variant.
 */
struct Variable *constraint_vertex_as_variable(const struct ConstraintVertex *vertex);

/**
 * Unwraps the <code>ConstraintVertex</code> instance as a Label.
 * Will panic if the instance is not a Label variant.
 */
struct Concept *constraint_vertex_as_label(const struct ConstraintVertex *vertex);

/**
 * Unwraps the <code>ConstraintVertex</code> instance as a Value.
 * Will panic if the instance is not a Value variant.
 */
struct Concept *constraint_vertex_as_value(const struct ConstraintVertex *vertex);

/**
 * Unwraps the <code>ConstraintVertex</code> instance as a NamedRole.
 * 'links' & 'relates' constraints accept unscoped role names.
 * Since an unscoped role-name does not uniquely identify a role-type,
 *  (Different role-types belonging to different relation types may share the same name)
 *  an internal variable is introduced to handle the ambiguity
 * Will panic if the instance is not a NamedRole variant.
 */
struct NamedRole *constraint_vertex_as_named_role(const struct ConstraintVertex *vertex);

/**
 * Returns the role-type variable associated with the NamedRole.
 */
struct Variable *named_role_get_variable(const struct NamedRole *named_role);

/**
 * Returns the role name associated with the NamedRole.
 */
char *named_role_get_name(const struct NamedRole *named_role);

/**
 * Returns a u32 identifying the named role instance.
 * Meant to be used to implement hash, equality etc.
 */
uint32_t named_role_as_u32(const struct NamedRole *named_role);

/**
 * Returns a string representation of the NamedRole
 */
char *named_role_string_repr(const struct NamedRole *named_role);

/**
 *Forwards the <code>FunctionIterator</code> and returns the next <code>Function</code> if it exists, or null if there are no more elements.
 */
struct Function *function_iterator_next(struct FunctionIterator *it);

/**
 *Frees the native rust <code>FunctionIterator</code> object.
 */
void function_iterator_drop(struct FunctionIterator *it);

/**
 *Forwards the <code>ConjunctionIDIterator</code> and returns the next <code>ConjunctionID</code> if it exists, or null if there are no more elements.
 */
struct ConjunctionID *conjunction_id_iterator_next(struct ConjunctionIDIterator *it);

/**
 *Frees the native rust <code>ConjunctionIDIterator</code> object.
 */
void conjunction_id_iterator_drop(struct ConjunctionIDIterator *it);

/**
 *Forwards the <code>ConstraintWithSpanIterator</code> and returns the next <code>ConstraintWithSpan</code> if it exists, or null if there are no more elements.
 */
struct ConstraintWithSpan *constraint_with_span_iterator_next(struct ConstraintWithSpanIterator *it);

/**
 *Frees the native rust <code>ConstraintWithSpanIterator</code> object.
 */
void constraint_with_span_iterator_drop(struct ConstraintWithSpanIterator *it);

/**
 *Forwards the <code>ConstraintVertexIterator</code> and returns the next <code>ConstraintVertex</code> if it exists, or null if there are no more elements.
 */
struct ConstraintVertex *constraint_vertex_iterator_next(struct ConstraintVertexIterator *it);

/**
 *Frees the native rust <code>ConstraintVertexIterator</code> object.
 */
void constraint_vertex_iterator_drop(struct ConstraintVertexIterator *it);

/**
 *Forwards the <code>PipelineStageIterator</code> and returns the next <code>PipelineStage</code> if it exists, or null if there are no more elements.
 */
struct PipelineStage *pipeline_stage_iterator_next(struct PipelineStageIterator *it);

/**
 *Frees the native rust <code>SortVariableIterator</code> object.
 */
void sort_variable_iterator_drop(struct SortVariableIterator *it);

/**
 *Forwards the <code>ReduceAssignmentIterator</code> and returns the next <code>ReduceAssignment</code> if it exists, or null if there are no more elements.
 */
struct ReduceAssignment *reduce_assignment_iterator_next(struct ReduceAssignmentIterator *it);

/**
 *Frees the native rust <code>ReduceAssignmentIterator</code> object.
 */
void reduce_assignment_iterator_drop(struct ReduceAssignmentIterator *it);

/**
 *Forwards the <code>ReducerIterator</code> and returns the next <code>Reducer</code> if it exists, or null if there are no more elements.
 */
struct Reducer *reducer_iterator_next(struct ReducerIterator *it);

/**
 *Frees the native rust <code>ReducerIterator</code> object.
 */
void reducer_iterator_drop(struct ReducerIterator *it);

/**
 *Frees the native rust <code>PipelineStageIterator</code> object.
 */
void pipeline_stage_iterator_drop(struct PipelineStageIterator *it);

/**
 *Forwards the <code>SortVariableIterator</code> and returns the next <code>SortVariable</code> if it exists, or null if there are no more elements.
 */
struct SortVariable *sort_variable_iterator_next(struct SortVariableIterator *it);

/**
 *Forwards the <code>VariableAnnotationsIterator</code> and returns the next <code>VariableAnnotations</code> if it exists, or null if there are no more elements.
 */
struct VariableAnnotations *variable_annotations_iterator_next(struct VariableAnnotationsIterator *it);

/**
 *Frees the native rust <code>VariableAnnotationsIterator</code> object.
 */
void variable_annotations_iterator_drop(struct VariableAnnotationsIterator *it);

/**
 *Forwards the <code>VariableIterator</code> and returns the next <code>Variable</code> if it exists, or null if there are no more elements.
 */
struct Variable *variable_iterator_next(struct VariableIterator *it);

/**
 *Frees the native rust <code>VariableIterator</code> object.
 */
void variable_iterator_drop(struct VariableIterator *it);

/**
 *Frees the native rust <code>AnalyzedQuery</code> object.
 */
void analyzed_query_drop(struct AnalyzedQuery *obj);

/**
 *Frees the native rust <code>Conjunction</code> object.
 */
void conjunction_drop(struct Conjunction *obj);

/**
 *Frees the native rust <code>ConjunctionID</code> object.
 */
void conjunction_id_drop(struct ConjunctionID *obj);

/**
 *Frees the native rust <code>Constraint</code> object.
 */
void constraint_with_span_drop(struct ConstraintWithSpan *obj);

/**
 *Frees the native rust <code>ConstraintVertex</code> object.
 */
void constraint_vertex_drop(struct ConstraintVertex *obj);

/**
 *Frees the native rust <code>Fetch</code> object.
 */
void fetch_drop(struct Fetch *obj);

/**
 *Frees the native rust <code>Function</code> object.
 */
void function_drop(struct Function *obj);

/**
 *Frees the native rust <code>NamedRole</code> object.
 */
void named_role_drop(struct NamedRole *obj);

/**
 *Frees the native rust <code>ReturnOperation</code> object.
 */
void return_operation_drop(struct ReturnOperation *obj);

/**
 *Frees the native rust <code>Pipeline</code> object.
 */
void pipeline_drop(struct Pipeline *obj);

/**
 *Frees the native rust <code>PipelineStage</code> object.
 */
void pipeline_stage_drop(struct PipelineStage *obj);

/**
 *Frees the native rust <code>Reducer</code> object.
 */
void reducer_drop(struct Reducer *obj);

/**
 *Frees the native rust <code>ReduceAssignment</code> object.
 */
void reduce_assignment_drop(struct ReduceAssignment *obj);

/**
 *Frees the native rust <code>SortVariable</code> object.
 */
void sort_variable_drop(struct SortVariable *obj);

/**
 *Frees the native rust <code>VariableAnnotations</code> object.
 */
void variable_annotations_drop(struct VariableAnnotations *obj);

/**
 *Frees the native rust <code>Variable</code> object.
 */
void variable_drop(struct Variable *obj);

/**
 * Waits for and returns the result of the operation represented by the <code>QueryAnswer</code> object.
 * In case the operation failed, the error flag will only be set when the promise is resolved.
 * The native promise object is freed when it is resolved.
 */
struct QueryAnswer *query_answer_promise_resolve(struct QueryAnswerPromise *promise);

/**
 * Frees the native rust <code>QueryAnswerPromise</code> object.
 */
void query_answer_promise_drop(struct QueryAnswerPromise *promise);

/**
 * Retrieves the executed query's type of the <code>QueryAnswer</code>.
 */
enum QueryType query_answer_get_query_type(const struct QueryAnswer *query_answer);

/**
 * Checks if the query answer is an <code>Ok</code>.
 */
bool query_answer_is_ok(const struct QueryAnswer *query_answer);

/**
 * Checks if the query answer is a <code>ConceptRowStream</code>.
 */
bool query_answer_is_concept_row_stream(const struct QueryAnswer *query_answer);

/**
 * Checks if the query answer is a <code>ConceptDocumentStream</code>.
 */
bool query_answer_is_concept_document_stream(const struct QueryAnswer *query_answer);

/**
 * Produces an <code>Iterator</code> over all <code>ConceptRow</code>s in this <code>QueryAnswer</code>.
 */
struct ConceptRowIterator *query_answer_into_rows(struct QueryAnswer *query_answer);

/**
 * Produces an <code>Iterator</code> over all JSON <code>ConceptDocument</code>s in this <code>QueryAnswer</code>.
 */
struct StringIterator *query_answer_into_documents(struct QueryAnswer *query_answer);

/**
 * Frees the native rust <code>QueryAnswer</code> object.
 */
void query_answer_drop(struct QueryAnswer *query_answer);

/**
 * Frees the native rust <code>ConceptRow</code> object.
 */
void concept_row_drop(struct ConceptRow *concept_row);

/**
 * Produces an <code>Iterator</code> over all <code>String</code> column names of the <code>ConceptRow</code>'s header.
 */
struct StringIterator *concept_row_get_column_names(const struct ConceptRow *concept_row);

/**
 * Retrieves the executed query's structure from the <code>ConceptRow</code>'s header, if set.
 * It must be requested via "include query structure" in <code>QueryOptions</code>
 */
struct Pipeline *concept_row_get_query_structure(const struct ConceptRow *concept_row);

/**
 * Retrieves the executed query's type of the <code>ConceptRow</code>'s header.
 */
enum QueryType concept_row_get_query_type(const struct ConceptRow *concept_row);

/**
 * Produces an <code>Iterator</code> over all <code>Concepts</code> in this <code>ConceptRow</code>.
 */
struct ConceptIterator *concept_row_get_concepts(const struct ConceptRow *concept_row);

/**
 * Retrieves a concept for a given column name.
 */
struct Concept *concept_row_get(const struct ConceptRow *concept_row, const char *column_name);

/**
 * Retrieves a concept for a given column index.
 */
struct Concept *concept_row_get_index(const struct ConceptRow *concept_row, uintptr_t column_index);

/**
 * Retrieve the <code>ConjunctionID</code>s of <code>Conjunction</code>s that answered this row.
 * May be null.
 */
struct ConjunctionIDIterator *concept_row_involved_conjunctions(const struct ConceptRow *concept_row);

/**
 * Checks whether the provided <code>ConceptRow</code> objects are equal
 */
bool concept_row_equals(const struct ConceptRow *lhs, const struct ConceptRow *rhs);

/**
 * A string representation of this ConceptRow.
 */
char *concept_row_to_string(const struct ConceptRow *concept_row);

/**
 * Forwards the <code>StringIterator</code> and returns the next string if it exists,
 * or null if there are no more elements.
 */
char *string_iterator_next(struct StringIterator *it);

/**
 * Frees the native rust <code>StringIterator</code> object
 */
void string_iterator_drop(struct StringIterator *it);

/**
 * Checks if the error flag was set by the last operation.
 * If true, the error can be retrieved using \ref get_last_error(void)
 */
bool check_error(void);

/**
 * Returns the error which set the error flag.
 */
struct Error *get_last_error(void);

/**
 * Frees the native rust <code>Error</code> object
 */
void error_drop(struct Error *error);

/**
 * Returns the error code of the <code>Error</code> object
 */
char *error_code(const struct Error *error);

/**
 * Returns the error message of the <code>Error</code> object
 */
char *error_message(const struct Error *error);

/**
 * Frees a native rust string.
 * _WARNING: Always use this function to free strings returned by the driver. Using the standard C free function will create a dangling reference on the rust side._
 */
void string_free(char *str);

/**
 * Waits for the operation represented by the <code>VoidPromise</code> to complete.
 * In case the operation failed, the error flag will only be set when the promise is resolved.
 * The native promise object is freed when it is resolved.
 */
void void_promise_resolve(struct VoidPromise *promise);

/**
 * Frees the native rust <code>VoidPromise</code> object.
 */
void void_promise_drop(struct VoidPromise *promise);

/**
 * Waits for and returns the result of the operation represented by the <code>BoolPromise</code> object.
 * In case the operation failed, the error flag will only be set when the promise is resolved.
 * The native promise object is freed when it is resolved.
 */
bool bool_promise_resolve(struct BoolPromise *promise);

/**
 * Frees the native rust <code>BoolPromise</code> object.
 */
void bool_promise_drop(struct BoolPromise *promise);

/**
 * Waits for and returns the result of the operation represented by the <code>BoolPromise</code> object.
 * In case the operation failed, the error flag will only be set when the promise is resolved.
 * The native promise object is freed when it is resolved.
 */
char *string_promise_resolve(struct StringPromise *promise);

/**
 * Frees the native rust <code>StringPromise</code> object.
 */
void string_promise_drop(struct StringPromise *promise);

/**
 * Forwards the <code>ConceptRowIterator</code> and returns the next <code>ConceptRow</code> if it exists,
 * or null if there are no more elements.
 */
struct ConceptRow *concept_row_iterator_next(struct ConceptRowIterator *it);

/**
 * Frees the native rust <code>ConceptRowIterator</code> object
 */
void concept_row_iterator_drop(struct ConceptRowIterator *it);

/**
 * Forwards the <code>ConceptIterator</code> and returns the next <code>Concept</code> if it exists,
 * or null if there are no more elements.
 */
struct Concept *concept_iterator_next(struct ConceptIterator *it);

/**
 * Frees the native rust <code>ConceptIterator</code> object
 */
void concept_iterator_drop(struct ConceptIterator *it);

/**
 * Frees the native rust <code>DatetimeAndTimeZone</code> object
 */
void datetime_and_time_zone_drop(struct DatetimeAndTimeZone *datetime_tz);

/**
 * Forwards the <code>StringAndOptValueIterator</code> and returns the next <code>StringAndOptValue</code> if it exists,
 * or null if there are no more elements.
 */
struct StringAndOptValue *string_and_opt_value_iterator_next(struct StringAndOptValueIterator *it);

/**
 * Frees the native rust <code>StringAndOptValueIterator</code> object
 */
void string_and_opt_value_iterator_drop(struct StringAndOptValueIterator *it);

/**
 * Frees the native rust <code>StringAndOptValue</code> object
 */
void string_and_opt_value_drop(struct StringAndOptValue *string_and_opt_value);

/**
 * Retrieves the unique id (IID) of this <code>Concept</code>.
 * If this is an Entity or Relation Instance, returns the IID of the instance.
 * Otherwise, returns null.
 */
char *concept_try_get_iid(struct Concept *instance);

/**
 * Retrieves the label of this <code>Concept</code>.
 * If this is an <code>Instance</code>, returns the label of the type of this instance ("unknown" if type fetching is disabled).
 * If this is a <code>Value</code>, returns the label of the value type of the value.
 * If this is a <code>Type</code>, returns the label of the type.
 */
char *concept_get_label(const struct Concept *concept);

/**
 * Retrieves the optional label of this <code>Concept</code>.
 * If this is an <code>Instance</code>, returns the label of the type of this instance (None if type fetching is disabled).
 * If this is a <code>Value</code>, returns the label of the value type of the value.
 * If this is a <code>Type</code>, returns the label of the type.
 */
char *concept_try_get_label(const struct Concept *concept);

/**
 * Retrieves the value type of this <code>Concept</code>, if it exists.
 * If this is an <code>Attribute</code> instance, returns the value type of this instance.
 * If this is a <code>Value</code>, returns its value type.
 * If this is an <code>AttributeType</code>, returns the value type that the schema permits for the attribute type, if one is defined.
 * Otherwise, returns null.
 */
char *concept_try_get_value_type(const struct Concept *concept);

/**
 * Retrieves the value of this <code>Concept</code>, if it exists.
 * If this is an <code>Attribute</code> instance, returns the value of this instance.
 * If this a <code>Value</code>, returns the value.
 * Otherwise, returns null.
 */
struct Concept *concept_try_get_value(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>boolean</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_boolean(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>integer</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_integer(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>double</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_double(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>decimal</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_decimal(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>string</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_string(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>date</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_date(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>datetime</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_datetime(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>datetime-tz</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_datetime_tz(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>duration</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_duration(const struct Concept *concept);

/**
 * Returns <code>true</code> if the value which this <code>Concept</code> holds is of type <code>struct</code>.
 * Otherwise, returns <code>false</code>.
 */
bool concept_is_struct(const struct Concept *concept);

/**
 * Returns a <code>boolean</code> value of this value concept.
 * If the value has another type, the error is set.
 */
bool concept_get_boolean(const struct Concept *concept);

/**
 * Returns the <code>integer</code> value of this value concept.
 * If the value has another type, the error is set.
 */
int64_t concept_get_integer(const struct Concept *concept);

/**
 * Returns the <code>double</code> value of this value concept.
 * If the value has another type, the error is set.
 */
double concept_get_double(const struct Concept *concept);

/**
 * Returns the <code>decimal</code> value of this value concept.
 * If the value has another type, the error is set.
 */
struct Decimal concept_get_decimal(const struct Concept *concept);

/**
 * Returns the <code>string</code> value of this value concept.
 * If the value has another type, the error is set.
 */
char *concept_get_string(const struct Concept *concept);

/**
 * Returns the value of this date value concept as seconds since the start of the UNIX epoch.
 * If the value has another type, the error is set.
 */
int64_t concept_get_date_as_seconds(const struct Concept *concept);

/**
 * Returns the value of this datetime value concept as seconds and nanoseconds parts since the start of the UNIX epoch.
 * If the value has another type, the error is set.
 */
struct DatetimeInNanos concept_get_datetime(const struct Concept *concept);

/**
 * Returns the value of this datetime-tz value concept as seconds and nanoseconds parts since the start of the UNIX epoch and timezone information.
 * If the value has another type, the error is set.
 */
struct DatetimeAndTimeZone *concept_get_datetime_tz(const struct Concept *concept);

/**
 * Returns the value of this duration value.
 * If the value has another type, the error is set.
 */
struct Duration concept_get_duration(const struct Concept *concept);

/**
 * Returns the value of this struct value concept represented as an iterator of {field_name: value?} pairs.
 * If the value has another type, the error is set.
 */
struct StringAndOptValueIterator *concept_get_struct(const struct Concept *concept);

/**
 * Checks whether the provided <code>Concept</code> objects are equal
 */
bool concept_equals(const struct Concept *lhs, const struct Concept *rhs);

/**
 * Frees the native rust <code>Concept</code> object
 */
void concept_drop(struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is an <code>EntityType</code>.
 */
bool concept_is_entity_type(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is a <code>RelationType</code>.
 */
bool concept_is_relation_type(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is an <code>AttributeType</code>.
 */
bool concept_is_attribute_type(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is a <code>RoleType</code>.
 */
bool concept_is_role_type(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is an <code>Entity</code>.
 */
bool concept_is_entity(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is a <code>Relation</code>.
 */
bool concept_is_relation(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is an <code>Attribute</code>.
 */
bool concept_is_attribute(const struct Concept *concept);

/**
 * Checks if this <code>Concept</code> is a <code>Value</code>.
 */
bool concept_is_value(const struct Concept *concept);

/**
 * A string representation of this <code>Concept</code> object.
 */
char *concept_to_string(const struct Concept *concept);

/**
 * Retrieves the type which this ``Entity`` belongs to.
 */
struct Concept *entity_get_type(const struct Concept *entity);

/**
 * Retrieves the type which this ``Relation`` belongs to.
 */
struct Concept *relation_get_type(const struct Concept *relation);

/**
 * Retrieves the type which this ``Attribute`` belongs to.
 */
struct Concept *attribute_get_type(const struct Concept *attribute);

/**
 * Creates a new <code>Credentials</code> for connecting to TypeDB Server.
 *
 * @param username The name of the user to connect as
 * @param password The password for the user
 */
struct Credentials *credentials_new(const char *username, const char *password);

/**
 * Frees the native rust <code>Credentials</code> object
 */
void credentials_drop(struct Credentials *credentials);

/**
 * Frees the native rust <code>Database</code> object.
 */
void database_close(const struct Database *database);

/**
 * The <code>Database</code> name as a string.
 */
char *database_get_name(const struct Database *database);

/**
 * Deletes this database.
 *
 * @param database The <code>Database</code> to delete.
 */
void database_delete(const struct Database *database);

/**
 * A full schema text as a valid TypeQL define query string.
 *
 * @param database The <code>Database</code> to get the schema from.
 */
char *database_schema(const struct Database *database);

/**
 * The types in the schema as a valid TypeQL define query string.
 *
 * @param database The <code>Database</code> to get the type schema from.
 */
char *database_type_schema(const struct Database *database);

/**
 * Export a database into a schema definition and a data files saved to the disk.
 * This is a blocking operation and may take a significant amount of time depending on the database size.
 *
 * @param database The <code>Database</code> object to export from.
 * @param schema_file The path to the schema definition file to be created.
 * @param data_file The path to the data file to be created.
 */
void database_export_to_file(const struct Database *database,
                             const char *schema_file,
                             const char *data_file);

/**
 * Forwards the <code>DatabaseIterator</code> and returns the next <code>Database</code> if it exists,
 * or null if there are no more elements.
 */
const struct Database *database_iterator_next(struct DatabaseIterator *it);

/**
 * Frees the native rust <code>DatabaseIterator</code> object.
 */
void database_iterator_drop(struct DatabaseIterator *it);

/**
 * Returns a <code>DatabaseIterator</code> over all databases present on the TypeDB server.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 */
struct DatabaseIterator *databases_all(struct TypeDBDriver *driver);

/**
 * Checks if a database with the given name exists.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param name The name of the database.
 */
bool databases_contains(struct TypeDBDriver *driver, const char *name);

/**
 * Retrieves the database with the given name.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param name The name of the database.
 */
const struct Database *databases_get(struct TypeDBDriver *driver, const char *name);

/**
 * Creates a database with the given name.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param name The name of the database to be created.
 */
void databases_create(struct TypeDBDriver *driver, const char *name);

/**
 * Creates a database with the given name based on previously exported another database's data
 * loaded from a file.
 * This is a blocking operation and may take a significant amount of time depending on the database
 * size.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param name The name of the database to be created.
 * @param schema The schema definition query string for the database.
 * @param data_file The exported database file path to import the data from.
 */
void databases_import_from_file(struct TypeDBDriver *driver,
                                const char *name,
                                const char *schema,
                                const char *data_file);

/**
 * Open a TypeDB Driver to a TypeDB server available at the provided address.
 *
 * @param address The address on which the TypeDB Server is running
 * @param credentials The <code>Credentials</code> to connect with
 * @param driver_options The <code>DriverOptions</code> to connect with
 * @param driver_lang The language of the driver connecting to the server.
 *        Nullable: pass NULL to default to "c".
 */
struct TypeDBDriver *driver_new(const char *address,
                                const struct Credentials *credentials,
                                const struct DriverOptions *driver_options,
                                const char *driver_lang);

/**
 * Open a TypeDB Driver to a TypeDB cluster available at the provided addresses.
 *
 * @param addresses A null-terminated array holding the server addresses on for connection
 * @param credentials The <code>Credentials</code> to connect with
 * @param driver_options The <code>DriverOptions</code> to connect with
 * @param driver_lang The language of the driver connecting to the server.
 *        Nullable: pass NULL to default to "c".
 */
struct TypeDBDriver *driver_new_with_addresses(const char *const *addresses,
                                               const struct Credentials *credentials,
                                               const struct DriverOptions *driver_options,
                                               const char *driver_lang);

/**
 * Open a TypeDB Driver to a TypeDB cluster, using the provided address translation.
 *
 * @param public_addresses A null-terminated array holding the replica addresses on for connection.
 * @param private_addresses A null-terminated array holding the private replica addresses, configured on the server side.
 * This array <i>must</i> have the same length as <code>public_addresses</code>.
 * @param credentials The <code>Credentials</code> to connect with
 * @param driver_options The <code>DriverOptions</code> to connect with
 * @param driver_lang The language of the driver connecting to the server.
 *        Nullable: pass NULL to default to "c".
 */
struct TypeDBDriver *driver_new_with_address_translation(const char *const *public_addresses,
                                                         const char *const *private_addresses,
                                                         const struct Credentials *credentials,
                                                         const struct DriverOptions *driver_options,
                                                         const char *driver_lang);

/**
 * Closes the <code>TypeDBDriver</code>. Before instantiating a new driver, the driver that’s currently open should first be closed.
 * Closing a driver frees the underlying Rust object.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 */
void driver_close(struct TypeDBDriver *driver);

/**
 * Forcibly closes the <code>TypeDBDriver</code>. To be used in exceptional cases.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 */
void driver_force_close(struct TypeDBDriver *driver);

/**
 * Checks whether this connection is presently open.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 */
bool driver_is_open(const struct TypeDBDriver *driver);

/**
 * Retrieves the server version and distribution information.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param server_routing The server routing directive to use for the operation. Auto if null.
 */
struct ServerVersion *driver_server_version(const struct TypeDBDriver *driver,
                                            const struct ServerRouting *server_routing);

/**
 * Retrieves the servers.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param server_routing The server routing directive to use for the operation. Auto if null.
 */
struct ServerIterator *driver_servers(const struct TypeDBDriver *driver,
                                      const struct ServerRouting *server_routing);

/**
 * Retrieves the server's primary server, if exists.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param server_routing The server routing directive to use for the operation. Auto if null.
 */
struct Server *driver_primary_server(const struct TypeDBDriver *driver,
                                     const struct ServerRouting *server_routing);

/**
 * Creates a new <code>DriverOptions</code> for connecting to TypeDB Server using custom TLS settings.
 * WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.
 */
struct DriverOptions *driver_options_new(const struct DriverTlsConfig *tls_config);

/**
 * Frees the native rust <code>DriverOptions</code> object.
 */
void driver_options_drop(struct DriverOptions *driver_options);

/**
 * Overrides the TLS configuration on <code>DriverOptions</code>.
 * WARNING: Disabled TLS settings will make the driver sending passwords as plaintext.
 */
void driver_options_set_tls_config(struct DriverOptions *options,
                                   const struct DriverTlsConfig *tls_config);

/**
 * Returns the TLS Config set for this <code>DriverOptions</code> object.
 * Specifies the TLS configuration of the connection to TypeDB.
 */
struct DriverTlsConfig *driver_options_get_tls_config(const struct DriverOptions *options);

/**
 * Sets the number of times the driver retries finding and re-routing to the primary replica
 * on connection failures. This value is used both for polling during leader election (up to
 * N+1 attempts with a 2-second sleep between each) and for re-executing a failed request on
 * a newly discovered primary. Defaults to 1.
 */
void driver_options_set_primary_failover_retries(struct DriverOptions *options,
                                                 int64_t primary_failover_retries);

/**
 * Returns the value set for the primary failover retries limit in this <code>DriverOptions</code> object.
 * Sets the number of times the driver retries finding and re-routing to the primary replica
 * on connection failures. This value is used both for polling during leader election (up to
 * N+1 attempts with a 2-second sleep between each) and for re-executing a failed request on
 * a newly discovered primary.
 */
int64_t driver_options_get_primary_failover_retries(const struct DriverOptions *options);

/**
 * Sets the maximum time (in milliseconds) to wait for a response to a unary RPC request.
 * This applies to operations like database creation, user management, and initial
 * transaction opening. It does NOT apply to operations within transactions (queries, commits).
 * Set to 0 to disable the timeout (not recommended for production use).
 * Defaults to 2 hours (7200000 milliseconds).
 */
void driver_options_set_request_timeout_millis(struct DriverOptions *options,
                                               int64_t timeout_millis);

/**
 * Returns the request timeout in milliseconds set for this <code>DriverOptions</code> object.
 * Specifies the maximum time to wait for a response to a unary RPC request.
 * This applies to operations like database creation, user management, and initial
 * transaction opening. It does NOT apply to operations within transactions (queries, commits).
 */
int64_t driver_options_get_request_timeout_millis(const struct DriverOptions *options);

/**
 * Creates a new <code>DriverTlsConfig</code> with TLS disabled.
 */
struct DriverTlsConfig *driver_tls_config_new_disabled(void);

/**
 * Creates a new <code>DriverTlsConfig</code> with TLS enabled using system native trust roots.
 */
struct DriverTlsConfig *driver_tls_config_new_enabled_with_native_root_ca(void);

/**
 * Creates a new <code>DriverTlsConfig</code> with TLS enabled using a custom root CA certificate (PEM).
 */
struct DriverTlsConfig *driver_tls_config_new_enabled_with_root_ca_path(const char *tls_root_ca);

/**
 * Frees the native rust <code>DriverTlsConfig</code> object.
 */
void driver_tls_config_drop(struct DriverTlsConfig *tls_config);

/**
 * Returns whether TLS is enabled.
 */
bool driver_tls_config_is_enabled(const struct DriverTlsConfig *tls_config);

/**
 * Returns whether a custom root CA path is set.
 */
bool driver_tls_config_has_root_ca_path(const struct DriverTlsConfig *tls_config);

/**
 * Returns the TLS root CA set in this <code>DriverTlsConfig</code> object.
 * Panics if a custom root CA is absent.
 */
char *driver_tls_config_get_root_ca_path(const struct DriverTlsConfig *tls_config);

/**
 * Produces a new <code>QueryOptions</code> object.
 */
struct QueryOptions *query_options_new(void);

/**
 * Frees the native Rust <code>QueryOptions</code> object.
 */
void query_options_drop(struct QueryOptions *options);

/**
 * Explicitly sets the "include instance types" flag.
 * If set, specifies if types should be included in instance structs returned in ConceptRow answers.
 * This option allows reducing the amount of unnecessary data transmitted.
 */
void query_options_set_include_instance_types(struct QueryOptions *options,
                                              bool include_instance_types);

/**
 * Returns the value set for the "include instance types" flag in this <code>QueryOptions</code> object.
 * If set, specifies if types should be included in instance structs returned in ConceptRow answers.
 * This option allows reducing the amount of unnecessary data transmitted.
 */
bool query_options_get_include_instance_types(const struct QueryOptions *options);

/**
 * Checks whether the "include instance types" flag was explicitly set for this <code>QueryOptions</code> object.
 */
bool query_options_has_include_instance_types(const struct QueryOptions *options);

/**
 * Explicitly sets the prefetch size.
 * If set, specifies the number of extra query responses sent before the client side has to re-request more responses.
 * Increasing this may increase performance for queries with a huge number of answers, as it can
 * reduce the number of network round-trips at the cost of more resources on the server side.
 * Minimal value: 1.
 */
void query_options_set_prefetch_size(struct QueryOptions *options,
                                     int64_t prefetch_size);

/**
 * Returns the value set for the prefetch size in this <code>QueryOptions</code> object.
 * If set, specifies the number of extra query responses sent before the client side has to re-request more responses.
 * Increasing this may increase performance for queries with a huge number of answers, as it can
 * reduce the number of network round-trips at the cost of more resources on the server side.
 * Minimal value: 1.
 */
int64_t query_options_get_prefetch_size(const struct QueryOptions *options);

/**
 * Checks whether the prefetch size was explicitly set for this <code>QueryOptions</code> object.
 */
bool query_options_has_prefetch_size(const struct QueryOptions *options);

/**
 * Explicitly set the prefetch size.
 * If set, it requests the server to include the query structure in the answer header.
 */
void query_options_set_include_query_structure(struct QueryOptions *options,
                                               bool include_query_structure);

/**
 * Returns the value set for 'include query structure' in this <code>QueryOptions</code> object.
 */
bool query_options_get_include_query_structure(const struct QueryOptions *options);

/**
 * Checks whether the prefetch size was explicitly set for this <code>QueryOptions</code> object.
 */
bool query_options_has_include_query_structure(const struct QueryOptions *options);

/**
 * Forwards the <code>ServerIterator</code> and returns the next <code>Server</code> if it exists,
 * or null if there are no more elements.
 */
struct Server *server_iterator_next(struct ServerIterator *it);

/**
 * Frees the native rust <code>ServerIterator</code> object.
 */
void server_iterator_drop(struct ServerIterator *it);

/**
 * Frees the native rust <code>Server</code> object.
 */
void server_drop(struct Server *server_info);

/**
 * Returns the id of this server.
 */
int64_t server_get_id(const struct Server *server_info);

/**
 * Returns the address this server is hosted at.
 */
char *server_get_address(const struct Server *server_info);

/**
 * Returns whether the role of this server is set.
 */
bool server_has_role(const struct Server *server_info);

/**
 * Returns whether this is the primary server of the cluster or any of the supporting roles.
 */
enum ReplicationRole server_get_role(const struct Server *server_info);

/**
 * Checks whether this is the primary server of the cluster.
 */
bool server_is_primary(const struct Server *server_info);

/**
 * Returns whether the cluster protocol 'term' of this server exists.
 */
bool server_has_term(const struct Server *server_info);

/**
 * Returns the cluster protocol 'term' of this server.
 */
int64_t server_get_term(const struct Server *server_info);

/**
 * Creates an automatic <code>ServerRouting</code> object.
 */
struct ServerRouting *server_routing_auto(void);

/**
 * Creates a server-specific <code>ServerRouting</code> object.
 *
 * @param address The address of the server to route to.
 */
struct ServerRouting *server_routing_direct(const char *address);

/**
 * Drops the <code>ServerRouting</code> object.
 */
void server_routing_drop(struct ServerRouting *server_routing);

/**
 * Frees the native rust <code>ServerVersion</code> object
 */
void server_version_drop(struct ServerVersion *server_version);

/**
 * Opens a transaction to perform read or write queries on the database connected to the session.
 *
 * @param databases The <code>DatabaseManager</code> object on this connection.
 * @param database_name The name of the database with which the transaction connects.
 * @param type_ The type of transaction to be created (Write / Read / Schema).
 * @param options <code>TransactionOptions</code> to configure the opened transaction.
 */
struct Transaction *transaction_new(struct TypeDBDriver *driver,
                                    const char *database_name,
                                    enum TransactionType type_,
                                    const struct TransactionOptions *options);

/**
 * Performs a TypeQL query in the transaction.
 *
 * @param transaction The <code>Transaction</code> to execute the query within.
 * @param query The query string.
 * @param options <code>QueryOptions</code> to configure the executed query.
 */
struct QueryAnswerPromise *transaction_query(struct Transaction *transaction,
                                             const char *query,
                                             const struct QueryOptions *options);

/**
 * Analyzes a TypeQL query in the transaction.
 *
 * @param transaction The <code>Transaction</code> to analyze the query within.
 * @param query The query string.
 */
struct AnalyzedQueryPromise *transaction_analyze(struct Transaction *transaction,
                                                 const char *query);

/**
 * Closes the transaction, waits for all callbacks to complete, then frees the memory.
 */
void transaction_drop_sync(struct Transaction *txn);

/**
 * Forcibly closes this transaction. Returns a resolvable promise.
 */
struct VoidPromise *transaction_close(struct Transaction *txn);

/**
 * Commits the changes made via this transaction to the TypeDB database.
 * Whether or not the transaction is commited successfully, the transaction is closed after
 * the commit call and the native rust object is freed.
 */
struct VoidPromise *transaction_commit(struct Transaction *txn);

/**
 * Rolls back the uncommitted changes made via this transaction.
 */
struct VoidPromise *transaction_rollback(const struct Transaction *txn);

/**
 * Checks whether this transaction is open.
 */
bool transaction_is_open(const struct Transaction *txn);

/**
 * Registers a callback function which will be executed when this transaction is closed.
 *
 * @param txn The transaction on which to register the callback
 * @param callback_id The argument to be passed to the callback function when it is executed.
 * @param callback The function to be called
 */
struct VoidPromise *transaction_on_close(const struct Transaction *txn,
                                         uintptr_t callback_id,
                                         void (*callback)(uintptr_t, struct Error*));

/**
 * Produces a new <code>TransactionOptions</code> object.
 */
struct TransactionOptions *transaction_options_new(void);

/**
 * Frees the native Rust <code>TransactionOptions</code> object.
 */
void transaction_options_drop(struct TransactionOptions *options);

/**
 * Explicitly sets a transaction timeout.
 * If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.
 */
void transaction_options_set_transaction_timeout_millis(struct TransactionOptions *options,
                                                        int64_t timeout_millis);

/**
 * Returns the value set for the transaction timeout in this <code>TransactionOptions</code> object.
 * If set, specifies a timeout for killing transactions automatically, preventing memory leaks in unclosed transactions.
 */
int64_t transaction_options_get_transaction_timeout_millis(const struct TransactionOptions *options);

/**
 * Checks whether the option for transaction timeout was explicitly set for this <code>TransactionOptions</code> object.
 */
bool transaction_options_has_transaction_timeout_millis(const struct TransactionOptions *options);

/**
 * Explicitly sets schema lock acquire timeout.
 * If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock.
 */
void transaction_options_set_schema_lock_acquire_timeout_millis(struct TransactionOptions *options,
                                                                int64_t timeout_millis);

/**
 * Returns the value set for the schema lock acquire timeout in this <code>TransactionOptions</code> object.
 * If set, specifies how long the driver should wait if opening a transaction is blocked by an exclusive schema write lock.
 */
int64_t transaction_options_get_schema_lock_acquire_timeout_millis(const struct TransactionOptions *options);

/**
 * Checks whether the option for schema lock acquire timeout was explicitly set for this <code>TransactionOptions</code> object.
 */
bool transaction_options_has_schema_lock_acquire_timeout_millis(const struct TransactionOptions *options);

/**
 * Frees the native rust <code>User</code> object.
 */
void user_drop(struct User *user);

/**
 * Returns the name of this user.
 */
char *user_get_name(struct User *user);

/**
 * Updates the password for the current authenticated user.
 *
 * @param user The user to update the password of - must be the current user.
 * @param password The new password.
 */
void user_update_password(struct User *user, const char *password);

/**
 * Deletes this user.
 *
 * @param user The <code>User</code> to delete.
 */
void user_delete(struct User *user);

/**
 * Forwards the <code>UserIterator</code> and returns the next <code>User</code> if it exists,
 * or null if there are no more elements.
 */
struct User *user_iterator_next(struct UserIterator *it);

/**
 * Frees the native rust <code>UserIterator</code> object.
 */
void user_iterator_drop(struct UserIterator *it);

/**
 * Retrieves all users which exist on the TypeDB server.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 */
struct UserIterator *users_all(const struct TypeDBDriver *driver);

/**
 * Checks if a user with the given name exists.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param username The username of the user.
 */
bool users_contains(const struct TypeDBDriver *driver, const char *username);

/**
 * Retrieves a user with the given name.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 * @param username The username of the user.
 */
struct User *users_get(const struct TypeDBDriver *driver, const char *username);

/**
 * Retrieves the username of the user who opened this connection.
 *
 * @param driver The <code>TypeDBDriver</code> object.
 */
struct User *users_get_current(const struct TypeDBDriver *driver);

/**
 * Creates a user with the given name &amp; password.
 *
 * @param username The username of the created user.
 * @param password The password of the created user.
 */
void users_create(const struct TypeDBDriver *driver, const char *username, const char *password);

/** @file */ // Tells doxygen to document this file.
